version: '3.8'
name: theRSSler

services:
  bot:
    image: node:22.11.0
    env_file: .env
    build:
      context: .
    environment:
      - TOKEN=${TOKEN}
      - GUILD_ID=${GUILD_ID}
      - CLIENT_ID=${CLIENT_ID}
      - ADMIN_USER_ID=${ADMIN_USER_ID} # Ensure you have a .env file with the TOKEN variable
    volumes:
      - .:/app # Mount the current directory to the container
    restart: unless-stopped
